# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: windows-latest

trigger: none

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- task: npmAuthenticate@0
  inputs:
    workingFile: .npmrc
  displayName: 'Azure Artifact Authenticate'

- script: |
    npm install
  displayName: 'NPM install'

- script: |
    npm run test:ci
  displayName: 'Run unit test'

- task: PublishTestResults@2
  displayName: 'Publish test results to pipelines'
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: './junit.xml'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage to pipelines'
  condition: succeededOrFailed()
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml
